name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_create-java-version-branch.yml@8bfa5fbef8b47c9e154c9996b17e527e6d0aee25
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Spotless",    "directory": ".github/ci/spotless"},
          {"name": "ArchUnit",    "directory": ".github/ci/archunit"},
          {"name": "ErrorProne",  "directory": ".github/ci/errorprone"},
          {"name": "SpotBugs",   "directory": ".github/ci/spotbugs"},
          {"name": "JUnit",      "directory": ".github/ci/junit"}
        ]
