name: Restore Branch From Backup

on:
  workflow_dispatch:

run-name: "Restore ${{ github.ref_name }} from ${{ github.ref_name }}-backup"

jobs:
  restore:
    uses: valkyrjaio/.github/.github/workflows/_restore-branch-from-backup.yml@2b8b906bbb5cbc98f568d2a5ac580092481c88ac
    permissions:
      contents: write
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
