name: Z Reusable Create Release

on:
  workflow_call:
    inputs:
      bump:
        description: 'Version component to bump'
        type: string
        required: true

jobs:
  check-version:
    uses: ./.github/workflows/_get-version-for-release.yml
    secrets: inherit
    with:
      bump: ${{ inputs.bump }}

  update-version-files:
    needs: check-version
    uses: ./.github/workflows/_update-version-files.yml
    secrets: inherit
    with:
      version: ${{ needs.check-version.outputs.version }}

  release:
    needs: [update-version-files, check-version]
    uses: ./.github/workflows/_release.yml
    secrets: inherit
    with:
      version: ${{ needs.check-version.outputs.version }}
