name: Z Reusable Create Version Branch

on:
  workflow_call:

jobs:
  get-version:
    uses: ./.github/workflows/_get-version.yml
    secrets: inherit

  create:
    needs: get-version
    uses: ./.github/workflows/_version-branch.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      branch: ${{ needs.get-version.outputs.branch }}
