name: Z Reusable Go Create Version Branch

on:
  workflow_call:
    inputs:
      dependencies:
        description: >
          JSON array of dependencies to check for outdated versions.
          Each item must have a "name" and "directory".
          Example: [{"name":"golangci-lint","directory":".github/ci/lint"}]
        type: string
        required: true
    secrets:
      VALKYRJA_GHA_APP_ID:
        description: 'App ID of the GitHub App that mints the token this workflow uses'
        required: true
      VALKYRJA_GHA_PRIVATE_KEY:
        description: 'Private key of the GitHub App that mints the token this workflow uses'
        required: true

jobs:
  check-outdated-dependencies:
    uses: ./.github/workflows/_go-check-outdated-dependencies.yml
    with:
      dependencies: ${{ inputs.dependencies }}

  get-version:
    needs: check-outdated-dependencies
    uses: ./.github/workflows/_get-version.yml
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}

  create-version-branch:
    needs: get-version
    uses: ./.github/workflows/_go-version-branch.yml
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      version: ${{ needs.get-version.outputs.version }}
      branch: ${{ needs.get-version.outputs.branch }}
