name: Z Reusable Python Release PyPI Publish

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        type: string
        default: '3.14'
    secrets:
      PYPI_API_TOKEN:
        description: 'API token that authenticates the upload to PyPI'
        required: true

jobs:
  pypi-publish:
    name: Publish to PyPI

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ github.ref_name }}

      - name: Setup uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Build distributions
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish

  wait-for-availability:
    name: Wait For Package Availability
    needs: [pypi-publish]
    uses: ./.github/workflows/_wait-for-package-availability.yml
    with:
      ecosystem: pypi
      wait-minutes: 15
