name: Z Reusable Python Create Version Branch

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        type: string
        default: '3.14'
      dependencies:
        description: >
          JSON array of dependencies to check for outdated versions.
          Each item must have a "name" and "directory".
          Example: [{"name":"Ruff","directory":".github/ci/ruff"}]
        type: string
        required: true

jobs:
  check-outdated-dependencies:
    uses: ./.github/workflows/_python-check-outdated-dependencies.yml
    secrets: inherit
    with:
      python-version: ${{ inputs.python-version }}
      dependencies: ${{ inputs.dependencies }}
      major-release: true

  get-version:
    needs: check-outdated-dependencies
    uses: ./.github/workflows/_get-version.yml
    secrets: inherit

  create-version-branch:
    needs: get-version
    uses: ./.github/workflows/_python-version-branch.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      branch: ${{ needs.get-version.outputs.branch }}
      python-version: ${{ inputs.python-version }}
