name: Commit Message Check

on:
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  commit-message-check:
    name: Commit Message Check
    uses: ./workflows/_commit-message-check.yml
    permissions:
      pull-requests: write
      contents: read
