name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: ./.github/workflows/_create-version-branch.yml
    secrets: inherit
