name: Create Repository

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Repository name (without org prefix)'
        type: string
        required: true
      description:
        description: 'Repository description'
        type: string
        required: true

run-name: "Create ${{ github.repository_owner }}/${{ inputs.name }}"

jobs:
  create-repo:
    uses: ./.github/workflows/_create-repo.yml
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      name: ${{ inputs.name }}
      description: ${{ inputs.description }}
