name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  get-version:
    uses: valkyrjaio/.github/.github/workflows/_get-version.yml@master
    secrets: inherit

  create:
    needs: get-version
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@master
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      branch: ${{ needs.get-version.outputs.branch }}