name: Enforce Repository Settings

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

run-name: Enforce repository settings across ${{ github.repository_owner }}

jobs:
  enforce:
    uses: valkyrjaio/.github/.github/workflows/_enforce-repo-settings.yml@master
    secrets: inherit
