name: Ensure Reusable Workflow Names

on:
  schedule:
    - cron: '0 13 * * 1'
  workflow_dispatch:

jobs:
  ensure-reusable-workflow-names:
    uses: ./.github/workflows/_ensure-reusable-workflow-names.yml
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
