name: Fix Trailing Newlines

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

jobs:
  fix-trailing-newlines:
    uses: ./.github/workflows/_fix-trailing-newlines.yml
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
