name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version component to bump'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - rc

run-name: "Release ${{ inputs.bump }} bump on ${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/_create-release.yml
    secrets: inherit
    with:
      bump: ${{ inputs.bump }}

  update-refs:
    name: Update Workflow Refs
    needs: release
    uses: ./.github/workflows/_update-github-workflow-refs.yml
    secrets: inherit
