name: Trailing Newline Check

on:
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  trailing-newline-check:
    name: Trailing Newline Check
    uses: ./.github/workflows/_trailing-newline-check.yml
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit