name: Update .github Workflow References

on:
  release:
    types: [published]
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

run-name: Update .github workflow refs to latest release across all repos

jobs:
  update-refs:
    if: github.event_name != 'release' || !github.event.release.prerelease
    uses: ./.github/workflows/_update-workflow-refs.yml
    secrets: inherit
    with:
      source-repo: .github
